import os
import random
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW

from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    get_linear_schedule_with_warmup
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

#########################
#### Data Locations #####
#########################

TRAIN_FILE = "train_processed_clean.csv"
VALIDATION_FILE = "validation_processed_clean.csv"

TEST_FILES = {
    "clean": "twitter_processed_clean.csv",
    "lowercase": "twitter_processed_lowercase.csv",
    "no_punctuation": "twitter_processed_nopunct.csv",
    "lowercase_no_punctuation": "twitter_processed_lower_nopunct.csv"
}

TEXT_COL = "processed_text"
LABEL_COL = "label"
POSITIVE_LABELS = {1}

MODEL_NAME = "bert-base-uncased"

#########################
#### Hyperparameters ####
#########################

# Current best settings (as of 5/9):
MAX_LEN = 96
TRAIN_BATCH_SIZE = 32
EVAL_BATCH_SIZE = 64
EPOCHS = 3
LEARNING_RATE = 1e-5
WEIGHT_DECAY = 0.0001
RANDOM_SEED = 42

# Set to None to use full training set
MAX_TRAIN_EXAMPLES = None

# Windows has trouble with multiprocessing, so leave at 0
NUM_WORKERS = 0

# Make sure CUDA settings work, otherwise takes too long
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
RESULTS_FILE = "bert_results_summary.csv"

if torch.cuda.is_available():
    torch.backends.cudnn.benchmark = True
    torch.set_float32_matmul_precision("high")


###############################################
#### Added seed for better reproducability ####
###############################################

def set_seed(seed=RANDOM_SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


###################################################
#### LABEL / DATA HELPERS generated by ChatGPT ####
###################################################

def convert_labels_to_binary(series):
    return series.apply(lambda x: 1 if x in POSITIVE_LABELS else 0)


def load_dataset(path, text_col=TEXT_COL, label_col=LABEL_COL):
    df = pd.read_csv(path)

    if text_col not in df.columns:
        raise ValueError(
            f"Missing text column '{text_col}' in {path}. "
            f"Found columns: {df.columns.tolist()}"
        )

    if label_col not in df.columns:
        raise ValueError(
            f"Missing label column '{label_col}' in {path}. "
            f"Found columns: {df.columns.tolist()}"
        )

    df = df.dropna(subset=[text_col, label_col]).copy()
    df[text_col] = df[text_col].astype(str)

    return df


def make_balanced_subset(df, max_examples):
    if max_examples is None or len(df) <= max_examples:
        return df

    # Separate classes explicitly (safer than groupby)
    df_pos = df[df[LABEL_COL] == 1]
    df_neg = df[df[LABEL_COL] == 0]

    n = max_examples // 2

    df_pos_sample = df_pos.sample(n=min(len(df_pos), n), random_state=RANDOM_SEED)
    df_neg_sample = df_neg.sample(n=min(len(df_neg), n), random_state=RANDOM_SEED)

    subset = pd.concat([df_pos_sample, df_neg_sample])
    subset = subset.sample(frac=1, random_state=RANDOM_SEED).reset_index(drop=True)

    return subset


############################
#### Dataset as a class ####
############################

# Needed dataset statistics stored for BERT, used csv conversion example from GitHub and modified for our use case:
class SarcasmDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=MAX_LEN):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            str(self.texts[idx]),
            add_special_tokens=True,
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_attention_mask=True,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(int(self.labels[idx]), dtype=torch.long)
        }


############################################
#### Dataloaded taken from BERT example ####
############################################

def make_dataloader(dataset, batch_size, shuffle):
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        pin_memory=torch.cuda.is_available(),
        persistent_workers=(NUM_WORKERS > 0)
    )


#######################
#### Training loop ####
#######################
# Taken from BERT example, modified for our use case 
# Had ChatGPT add progress bars to see progress

# Single epoch training loop, returns average loss for the epoch
def train_one_epoch(model, dataloader, optimizer, scheduler, device, scaler):
    model.train()
    total_loss = 0.0

    # MAKE SURE CUDA IS ENABLED IT TAKES SO LONG
    use_amp = torch.cuda.is_available()

    # tqdm progress bar for training loop
    for batch in tqdm(dataloader, desc="Training", leave=True):
        input_ids = batch["input_ids"].to(device, non_blocking=True)
        attention_mask = batch["attention_mask"].to(device, non_blocking=True)
        labels = batch["labels"].to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast(device_type="cuda", enabled=use_amp):
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )
            loss = outputs.loss

        if use_amp:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()

        scheduler.step()
        total_loss += loss.item()

    return total_loss / len(dataloader)


####################
#### Evaluation ####
####################

def evaluate_model(model, dataloader, device, dataset_name="dataset"):
    model.eval()

    all_labels = []
    all_preds = []
    all_probs = []

    # MAKE SURE CUDA IS ENABLED IT TAKES SO LONG
    use_amp = torch.cuda.is_available()

    with torch.no_grad():
        # tqdm progress bar for evaluation loop
        for batch in tqdm(dataloader, desc="Evaluating", leave=True):
            input_ids = batch["input_ids"].to(device, non_blocking=True)
            attention_mask = batch["attention_mask"].to(device, non_blocking=True)
            labels = batch["labels"].to(device, non_blocking=True)

            with torch.amp.autocast(device_type="cuda", enabled=use_amp):
                outputs = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask
                )

            logits = outputs.logits
            probs = torch.softmax(logits, dim=1)[:, 1]
            preds = torch.argmax(logits, dim=1)

            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    prec = precision_score(all_labels, all_preds, zero_division=0)
    rec = recall_score(all_labels, all_preds, zero_division=0)
    f1 = f1_score(all_labels, all_preds, zero_division=0)

    # Data formatted strange, had random column named "nan" that was causing errors, so added try/except to handle cases where only one class is present
    try:
        roc = roc_auc_score(all_labels, all_probs)
    except ValueError:
        roc = float("nan")

    try:
        pr_auc = average_precision_score(all_labels, all_probs)
    except ValueError:
        pr_auc = float("nan")

    cm = confusion_matrix(all_labels, all_preds)

    # Formatting done by ChatGPT to make results and graph more readable
    print("\n" + "=" * 70)
    print(f"Evaluation on: {dataset_name}")
    print("=" * 70)
    print(f"Accuracy     : {acc:.4f}")
    print(f"Precision    : {prec:.4f}")
    print(f"Recall       : {rec:.4f}")
    print(f"F1 Score     : {f1:.4f}")
    print(f"ROC AUC      : {roc:.4f}" if not np.isnan(roc) else "ROC AUC      : undefined")
    print(f"PR AUC       : {pr_auc:.4f}" if not np.isnan(pr_auc) else "PR AUC       : undefined")
    print("Confusion Matrix:")
    print(cm)
    print("\nClassification Report:")
    print(classification_report(all_labels, all_preds, zero_division=0))

    return {
        "dataset": dataset_name,
        "accuracy": acc,
        "precision": prec,
        "recall": rec,
        "f1": f1,
        "roc_auc": roc,
        "pr_auc": pr_auc
    }


##############
#### Main ####
##############

def main():
    # Added seed for reproducability
    set_seed()

    # Make sure CUDA is enabled, otherwise takes too long
    print(f"Using device: {DEVICE}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")

    # Diagnostic print check, program was getting stuck on loading data 
    # Had ChatGPT add progress bars and more diagnostic prints to see progress and where it was getting stuck, also added flush=True to make sure prints show up in correct order
    print("\nLoading training data...")
    train_df = load_dataset(TRAIN_FILE)

    # General structure taken from BERT example, and modified to fit our use case

    train_df = make_balanced_subset(train_df, MAX_TRAIN_EXAMPLES)

    train_texts = train_df[TEXT_COL].tolist()
    train_labels = convert_labels_to_binary(train_df[LABEL_COL]).tolist()

    print(f"Training examples: {len(train_texts)}")
    print(f"Positive class count: {sum(train_labels)}")
    print(f"Negative class count: {len(train_labels) - sum(train_labels)}")

    tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)

    train_dataset = SarcasmDataset(
        train_texts,
        train_labels,
        tokenizer,
        MAX_LEN
    )

    train_loader = make_dataloader(
        train_dataset,
        batch_size=TRAIN_BATCH_SIZE,
        shuffle=True
    )

    print("\nLoading validation data...", flush=True)
    validation_df = load_dataset(VALIDATION_FILE)

    validation_texts = validation_df[TEXT_COL].tolist()
    validation_labels = convert_labels_to_binary(validation_df[LABEL_COL]).tolist()

    validation_dataset = SarcasmDataset(
        validation_texts,
        validation_labels,
        tokenizer,
        MAX_LEN
    )

    validation_loader = make_dataloader(
        validation_dataset,
        batch_size=EVAL_BATCH_SIZE,
        shuffle=False
    )

    model = BertForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2
    )

    model.to(DEVICE)

    # AdamW seems to work best for BERT
    optimizer = AdamW(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY
    )

    total_steps = len(train_loader) * EPOCHS

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=0,
        num_training_steps=total_steps
    )

    scaler = torch.amp.GradScaler("cuda", enabled=torch.cuda.is_available())
    best_validation_f1 = 0.0
    best_epoch = 0

    print("\nTraining BERT...", flush=True)

    for epoch in range(EPOCHS):
        avg_train_loss = train_one_epoch(
            model,
            train_loader,
            optimizer,
            scheduler,
            DEVICE,
            scaler
        )

        print(f"\nEpoch {epoch + 1}/{EPOCHS}", flush=True)
        print(f"Train Loss: {avg_train_loss:.4f}", flush=True)

        validation_results = evaluate_model(
            model,
            validation_loader,
            DEVICE,
            dataset_name=f"validation_epoch_{epoch + 1}"
        )

        validation_f1 = validation_results["f1"]

        if validation_f1 > best_validation_f1:
            best_validation_f1 = validation_f1
            best_epoch = epoch + 1

            os.makedirs("bert_best_model", exist_ok=True)
            model.save_pretrained("bert_best_model")
            tokenizer.save_pretrained("bert_best_model")

            print(
                f"New best model saved from epoch {best_epoch} "
                f"with validation F1 = {best_validation_f1:.4f}",
                flush=True
            )

    print(
        f"\nBest validation epoch: {best_epoch} "
        f"with F1 = {best_validation_f1:.4f}",
        flush=True
    )

    os.makedirs("bert_model_output", exist_ok=True)
    model.save_pretrained("bert_model_output")
    tokenizer.save_pretrained("bert_model_output")

    all_results = []
    print("\nLoading best validation model for final testing...", flush=True)

    model = BertForSequenceClassification.from_pretrained("bert_best_model")
    model.to(DEVICE)

    for dataset_name, path in TEST_FILES.items():
        print(f"\nLoading test set: {dataset_name} from {path}")
        test_df = load_dataset(path)

        test_texts = test_df[TEXT_COL].tolist()
        test_labels = convert_labels_to_binary(test_df[LABEL_COL]).tolist()

        test_dataset = SarcasmDataset(
            test_texts,
            test_labels,
            tokenizer,
            MAX_LEN
        )

        test_loader = make_dataloader(
            test_dataset,
            batch_size=EVAL_BATCH_SIZE,
            shuffle=False
        )

        results = evaluate_model(
            model,
            test_loader,
            DEVICE,
            dataset_name
        )

        all_results.append(results)

    results_df = pd.DataFrame(all_results)

    print("\n" + "=" * 70)
    print("Summary of results")
    print("=" * 70)
    print(results_df.to_string(index=False))

    results_df.to_csv(RESULTS_FILE, index=False)
    print(f"\nSaved summary to {RESULTS_FILE}")


if __name__ == "__main__":
    main()