import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

#########################
#### Data Locations #####
#########################

TRAIN_FILE = "train_processed_clean.csv"

TEST_FILES = {
    "validation_clean": "validation_processed_clean.csv",
    "test_clean": "twitter_processed_clean.csv",
    "test_lowercase": "twitter_processed_lowercase.csv",
    "test_no_punctuation": "twitter_processed_nopunct.csv",
    "test_lowercase_no_punctuation": "twitter_processed_lower_nopunct.csv"
}

TEXT_COL = "processed_text"
LABEL_COL = "label"

POSITIVE_LABELS = {1}

#########################
#### Hyperparameters ####
#########################

# Current best settings (as of 4/29)
NGRAM_RANGE = (1, 2)
MIN_DF = 1
MAX_DF = 0.95
MAX_FEATURES = 75000
SUBLINEAR_TF = False
C_VAL = 1.0
SOLVER = "liblinear"

# Logistic regression settings
MAX_ITER = 1000
RANDOM_STATE = 42


###################################################
#### LABEL / DATA HELPERS generated by ChatGPT ####
###################################################

def convert_labels_to_binary(series):
    """
    Convert labels to binary 0/1.
    Positive labels are anything in POSITIVE_LABELS.
    Everything else becomes 0.
    """
    return series.apply(lambda x: 1 if x in POSITIVE_LABELS else 0)


def load_dataset(path, text_col=TEXT_COL, label_col=LABEL_COL):
    """
    Load a CSV and return text + binary labels.
    """
    df = pd.read_csv(path)

    if text_col not in df.columns:
        raise ValueError(f"Missing text column '{text_col}' in {path}. Found: {df.columns.tolist()}")

    if label_col not in df.columns:
        raise ValueError(f"Missing label column '{label_col}' in {path}. Found: {df.columns.tolist()}")

    df = df.dropna(subset=[text_col, label_col]).copy()
    df[text_col] = df[text_col].astype(str)

    X_text = df[text_col]
    y = convert_labels_to_binary(df[label_col])

    return df, X_text, y


####################
#### Evaluation ####
####################

def evaluate_model(model, X, y_true, dataset_name):

    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1]

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)

    # ROC AUC and PR AUC require both classes to be present
    # Data formatted strange, had random column named "nan" that was causing errors, so added try/except
 
    try:
        roc = roc_auc_score(y_true, y_prob)
    except ValueError:
        roc = float("nan")

    try:
        pr_auc = average_precision_score(y_true, y_prob)
    except ValueError:
        pr_auc = float("nan")

    cm = confusion_matrix(y_true, y_pred)

    # Formatting done by ChatGPT to make results and graph more readable
    print("\n" + "=" * 70)
    print(f"Evaluation on: {dataset_name}")
    print("=" * 70)
    print(f"Accuracy     : {acc:.4f}")
    print(f"Precision    : {prec:.4f}")
    print(f"Recall       : {rec:.4f}")
    print(f"F1 Score     : {f1:.4f}")
    print(f"ROC AUC      : {roc:.4f}" if not np.isnan(roc) else "ROC AUC      : undefined")
    print(f"PR AUC       : {pr_auc:.4f}" if not np.isnan(pr_auc) else "PR AUC       : undefined")
    print("Confusion Matrix:")
    print(cm)
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, zero_division=0))

    return {
        "dataset": dataset_name,
        "accuracy": acc,
        "precision": prec,
        "recall": rec,
        "f1": f1,
        "roc_auc": roc,
        "pr_auc": pr_auc
    }


#################################################
#### Print feature results - made by ChatGPT ####
#################################################

def print_top_features(vectorizer, model, top_n=20):
    """
    Print the most positive and most negative weighted features.
    Positive weights push toward sarcasm class.
    Negative weights push away from sarcasm class.
    """
    feature_names = np.array(vectorizer.get_feature_names_out())
    coefs = model.coef_[0]

    top_positive_idx = np.argsort(coefs)[-top_n:][::-1]
    top_negative_idx = np.argsort(coefs)[:top_n]

    print("\n" + "=" * 70)
    print("Top features pushing toward sarcasm (positive class)")
    print("=" * 70)
    for idx in top_positive_idx:
        print(f"{feature_names[idx]:<30} {coefs[idx]:.4f}")

    print("\n" + "=" * 70)
    print("Top features pushing away from sarcasm")
    print("=" * 70)
    for idx in top_negative_idx:
        print(f"{feature_names[idx]:<30} {coefs[idx]:.4f}")


##############
#### Main ####
##############

def main():
    # Diagnostic print check, program was getting stuck on loading data 
    # Had ChatGPT add diagnostic prints to see progress and where it was getting stuck, as 
    # well as format output to be more readable
    print("Loading training data...")
    train_df, X_train_text, y_train = load_dataset(TRAIN_FILE)

    print(f"Training examples: {len(train_df)}")
    print(f"Positive class count: {y_train.sum()}")
    print(f"Negative class count: {len(y_train) - y_train.sum()}")

    print("\nFitting TF-IDF vectorizer on training data...")
    vectorizer = TfidfVectorizer(
        ngram_range=NGRAM_RANGE,
        min_df=MIN_DF,
        max_df=MAX_DF,
        max_features=MAX_FEATURES,
        sublinear_tf=SUBLINEAR_TF
    )

    X_train = vectorizer.fit_transform(X_train_text)

    print(f"Training matrix shape: {X_train.shape}")
    print(f"Vocabulary size: {len(vectorizer.get_feature_names_out())}")

    print("\nTraining logistic regression model...")
    model = LogisticRegression(
        max_iter=MAX_ITER,
        random_state=RANDOM_STATE,
        C=C_VAL,
        solver=SOLVER,
        class_weight="balanced"
    )

    model.fit(X_train, y_train)

    all_results = []

    for dataset_name, path in TEST_FILES.items():
        print(f"\nLoading test set: {dataset_name} from {path}")
        test_df, X_test_text, y_test = load_dataset(path)

        # Important: use the SAME fitted vectorizer
        X_test = vectorizer.transform(X_test_text)

        results = evaluate_model(model, X_test, y_test, dataset_name)
        all_results.append(results)


    print_top_features(vectorizer, model, top_n=20)

    results_df = pd.DataFrame(all_results)

    print("\n" + "=" * 70)
    print("Summary of results")
    print("=" * 70)
    print(results_df.to_string(index=False))

    results_df.to_csv("tfidf_logreg_results_summary.csv", index=False)
    print("\nSaved summary to tfidf_logreg_results_summary.csv")


if __name__ == "__main__":
    main()